### ISSUE TITLE
iPadOS 18 Can't Enable Driver

### ISSUE THREAD

**Issue by blakekrone** [elgatosf/streamdeck-kit-ipad#43] opened 2024-10-03 03:09 UTC
Devices running iPadOS18 do not show the option to enable the driver under settings so no longer can use the app or any decks inside other apps.

![Screenshot 2024-10-02 at 10 08 58 PM](https://github.com/user-attachments/assets/95c14b3b-e325-44e0-88af-58e4ec0425fc)

iPad Pro 11-inch (M4) running 18.0 (22A3354)

Might be related to [https://developer.apple.com/forums/thread/763516?answerId=803923022#803923022](https://developer.apple.com/forums/thread/763516?answerId=803923022#803923022) but I haven't updated to 18.1 beta to test.

**Comment by rigor789** [comment] 2024-10-07 11:42
I just ran into this, and can confirm the iOS beta works.

**Comment by zahnooo** [comment] 2024-10-07 14:37
This is an Apple Issue on iPadOS 18.0 - Luckily, it has been fixed in iPadOS 18.1 which is now available publicly, too.

**Comment by zahnooo** [comment] 2024-10-08 08:28
My bad - iPadOS 18.1 is still in beta. With this version though it works. 
I have not tested if it works with the recently publicly released iPadOS 18.0.1.  

I will close this issue as soon as 18.1 is also publicly released.

**Comment by r-dent** [comment] 2024-10-29 09:24
Today Apple released iPadOS 18.1. The driver toggle is now appearing on our devices. So after updating, you should be able to finally use the app as intended.
@blakekrone @rigor789

**Closed by r-dent** 2024-10-29 09:24 UTC
